spring:
  jpa:
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        show_sql: true

    open-in-view: false

  mail:
    host: smtp.gmail.com
    port: 587
    username: slavikbylo@gmail.com
    password: 18032002Sl
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  datasource:
    url: jdbc:mysql://localhost:3306/users
    username: admin
    password: pass
    driver-class-name: com.mysql.cj.jdbc.Driver