spring:
  jpa:
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        show_sql: true

    open-in-view: false

  datasource:
    url: jdbc:mysql://localhost:3306/users
    username: admin
    password: pass
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8082
